lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Not Today
description: Not Today app
google_analytics:
theme: jekyll-theme-cayman